### PR TITLE
fix(agGridColumn): add missing attributes

### PR DESCRIPTION
**Pull request by mroseboom**
add support for the properties suppressToolPanel & suppressKeyboardEvent within the grid-column. This pr is a fix for issue [#25](https://github.com/ag-grid/ag-grid-aurelia/issues/25)

### CODE REVIEW

**Comment by mroseboom** [comment]
Is it an idea to use the [colDefUtil file](https://github.com/ag-grid/ag-grid/blob/master/src/ts/components/colDefUtil.ts) for the bindable properties?

Example usage:
```typescript
import { ColDefUtil } from "ag-grid/main";

@customElement('ag-grid-column')
@generateBindables(ColDefUtil.ALL_PROPERTIES) <--
// <slot> is required for @children to work.  https://github.com/aurelia/templating/issues/451#issuecomment-254206622
@inlineView(`<template><slot></slot></template>`)
@autoinject()
export class AgGridColumn {
   ...
}
```

**Comment by mroseboom** [comment]
@seanlandsman Do you have an idea when this pr can be merged?

**Comment by mroseboom** [comment]
any update on when this pull-request can be reviewed/merged?

**Comment by seanlandsman** [comment]
Hi

Apologies for the delay - this project is now deprecated. The replacement repo can be found at https://github.com/ag-grid/ag-grid.

I've manually taken this PR and applied it to the new repo. The changes will be available in the next release.

thanks for the PR!

**Pull request closed without merging**
